# Generated by Django 4.0.3 on 2024-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_number',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='bin_size',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='closet_name',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='binvo',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
